# Site settings
title: Bob Planet - 우리가 만드는 식단앱
email: bobplanet.team@gmail.com
description: BOB planet이 매일 The Planet 식당메뉴를 알려드립니다. <br />매일 점심/저녁 메뉴를 미리 푸쉬받아보세요.
# baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://bobplanet.github.io" # the base hostname & protocol for your site
twitter_username: dusskapark
github_username:  dusskapark

# Build settings
markdown: kramdown

# Analytics settings
analytics_param: bobp_userId
ga_trackid_web: UA-71027941-2
ga_trackid_rollup: UA-71027941-3
mixpanel_trackid: 36cc8303f20d992326aa63283098079c
